target: main.o bubble.o database.o db.o parse.o set.o stack.o sum.o bSearch.o
	gcc -o target main.c bSearch.c bubble.c database.c db.c defs.h parse.c set.c sortAndSearch.h stack.c sum.c
clean:
	rm *.o target
